const menuLsit = {
  'icon': 'bars',
  'title': '智能环控系统',
  'href': '/unit-evcbiz',
  'spread': false,
  'path': '/bizManager/unit-evcbiz',
  'frontendRoutePath': '/intelligent-control',
  'component': null,
  'authority': null,
  'redirect': null,
  'code': 'unit-evcbiz',
  'appCode': 'unit-evc',
  'label': null,
  'url': null,
  'id': '5Vcq9wmcrBB5vzVjBGoQvj',
  'parentId': 'muyuan_menu_root',
  'orderNum': 33,
  'children': [
    {
      'icon': 'Map',
      'title': '集团运维地图',
      'href': '/devicesDistributedMap',
      'spread': false,
      'path': '/bizManager/unit-evcbiz/devicesDistributedMap',
      'frontendRoutePath': '/intelligent-control/devicesDistributeChineseMap',
      'component': null,
      'authority': null,
      'redirect': null,
      'code': 'devicesDistributedMap',
      'appCode': 'unit-evc',
      'label': null,
      'url': null,
      'id': '5VgyWSzE576sLZzRakr2Ee',
      'parentId': '5Vcq9wmcrBB5vzVjBGoQvj',
      'orderNum': 4,
      'children': []
    },
    {
      'icon': 'Device-Preview',
      'title': '场区设备概览',
      'href': '/fieldDeviceOverview',
      'spread': false,
      'path': '/bizManager/unit-evcbiz/fieldDeviceOverview',
      'frontendRoutePath': '/intelligent-control/fieldDeviceOverview',
      'component': null,
      'authority': null,
      'redirect': null,
      'code': 'fieldDeviceOverview',
      'appCode': 'unit-evc',
      'label': null,
      'url': null,
      'id': '2EcUx189vehIxPrNj38AJr',
      'parentId': '5Vcq9wmcrBB5vzVjBGoQvj',
      'orderNum': 5,
      'children': []
    },
    {
      'icon': 'lock',
      'title': '温度数据导出',
      'href': '/tempSensor',
      'spread': false,
      'path': '/bizManager/unit-evcbiz/tempSensor',
      'component': null,
      'authority': null,
      'redirect': null,
      'code': 'tempSensor',
      'appCode': 'unit-evc',
      'label': null,
      'url': null,
      'id': '3gYfJltI5QPHsqCGaHQ3Yk',
      'parentId': '5Vcq9wmcrBB5vzVjBGoQvj',
      'orderNum': 6,
      'children': []
    },
    {
      'icon': 'Information-Maintenance',
      'title': '基础信息维护',
      'href': '/unit-evcMaintainBaseInfo',
      'spread': false,
      'path': '/intelligent-control/baseInfo/fieldWindMachineConfig',
      'frontendRoutePath': '/intelligent-control/baseInfo',
      'component': null,
      'authority': null,
      'redirect': null,
      'code': 'unit-evcMaintainBaseInfo',
      'appCode': 'unit-evc',
      'label': null,
      'url': null,
      'id': '44PvV2T26BSfTPr4GDAnCN',
      'parentId': '5Vcq9wmcrBB5vzVjBGoQvj',
      'orderNum': 3,
      'children': [
        {
          'icon': 'abcd',
          'title': '控制器信息维护',
          'href': '/evcControllerMaintain',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/baseInfoMaintain/evcControllerMaintain',
          'frontendRoutePath': '/intelligent-control/baseInfo/controllerMaintain',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'evcControllerMaintain',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '6shMigCrNhm0RlMRNZGGvS',
          'parentId': '44PvV2T26BSfTPr4GDAnCN',
          'orderNum': 1,
          'children': [
            {
              'icon': 'lock',
              'title': '台达信息维护',
              'href': '/plcInfoMaintain',
              'spread': false,
              'path': '/bizManager/unit-evcbiz/baseInfoMaintain/plcInfoMaintain',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'plcInfoMaintain',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '76QsL9coBVKmjcjdKmPBNJ',
              'parentId': '6shMigCrNhm0RlMRNZGGvS',
              'orderNum': 1,
              'children': []
            },
            {
              'icon': 'abcd',
              'title': '自研/华诚信息维护',
              'href': '/deviceInfoMaintain',
              'spread': false,
              'path': '/bizManager/unit-evcbiz/baseInfoMaintain/deviceInfoMaintain',
              'frontendRoutePath': '/intelligent-control/baseInfo/controllerMaintain/deviceInformation',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'deviceInfoMaintain',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '6EqSsZryKDyz5YGdhQdi7x',
              'parentId': '6shMigCrNhm0RlMRNZGGvS',
              'orderNum': 2,
              'children': [
                // {
                //   'icon': 'abcd',
                //   'title': '我是第四级的显示',
                //   'href': '/deviceInfoMaintain',
                //   'spread': false,
                //   'path': '/bizManager/unit-evcbiz/baseInfoMaintain/deviceInfoMaintain',
                //   'frontendRoutePath': '/intelligent-control/baseInfo/controllerMaintain/deviceInformation',
                //   'component': null,
                //   'authority': null,
                //   'redirect': null,
                //   'code': 'deviceInfoMaintain',
                //   'appCode': 'unit-evc',
                //   'label': null,
                //   'url': null,
                //   'id': '6EqSsZryKDyz5YGdhQdi7x',
                //   'parentId': '6shMigCrNhm0RlMRNZGGvS',
                //   'orderNum': 3,
                //   'children': [
                //     {
                //       'icon': 'abcd',
                //       'title': '我是第五级的显示',
                //       'href': '/deviceInfoMaintain',
                //       'spread': false,
                //       'path': '/bizManager/unit-evcbiz/baseInfoMaintain/deviceInfoMaintain',
                //       'frontendRoutePath': '/intelligent-control/baseInfo/controllerMaintain/deviceInformation',
                //       'component': null,
                //       'authority': null,
                //       'redirect': null,
                //       'code': 'deviceInfoMaintain',
                //       'appCode': 'unit-evc',
                //       'label': null,
                //       'url': null,
                //       'id': '6EqSsZryKDyz5YGdhQdi7x',
                //       'parentId': '6shMigCrNhm0RlMRNZGGvS',
                //       'orderNum': 4,
                //       'children': []
                //     }
                //   ]
                // }
              ]
            },
            {
              'icon': 'lock',
              'title': '楼房猪舍控制器信息维护',
              'href': '/buildingControllerMaintain',
              'spread': false,
              'path': '/bizManager/unit-evcbiz/baseInfoMaintain/evcControllerMaintain/buildingControllerMaintain',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'buildingControllerMaintain',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '6eXOE5t9aSlqd4vUiK8KYX',
              'parentId': '6shMigCrNhm0RlMRNZGGvS',
              'orderNum': 5,
              'children': [
                {
                  'icon': 'lock',
                  'title': '环控主控制器信息维护',
                  'href': '/roofMainControllerMaintain',
                  'spread': false,
                  'path': '/bizManager/unit-evcbiz/baseInfoMaintain/evcControllerMaintain/roofMainControllerMaintain',
                  'component': null,
                  'authority': null,
                  'redirect': null,
                  'code': 'roofMainControllerMaintain',
                  'appCode': 'unit-evc',
                  'label': null,
                  'url': null,
                  'id': '5YvoyOZ9ISkD0zEaydHen7',
                  'parentId': '6eXOE5t9aSlqd4vUiK8KYX',
                  'orderNum': 3,
                  'children': []
                },
                {
                  'icon': 'lock',
                  'title': '风机控制器信息维护',
                  'href': '/roofSubControllerMaintain',
                  'spread': false,
                  'path': '/bizManager/unit-evcbiz/baseInfoMaintain/evcControllerMaintain/roofSubControllerMaintain',
                  'component': null,
                  'authority': null,
                  'redirect': null,
                  'code': 'roofSubControllerMaintain',
                  'appCode': 'unit-evc',
                  'label': null,
                  'url': null,
                  'id': '4HAlLfzR60Tm6mG7857HGj',
                  'parentId': '6eXOE5t9aSlqd4vUiK8KYX',
                  'orderNum': 4,
                  'children': []
                },
                {
                  'icon': 'lock',
                  'title': '单元控制器信息维护',
                  'href': '/unitControllerMaintain',
                  'spread': false,
                  'path': '/bizManager/unit-evcbiz/baseInfoMaintain/evcControllerMaintain/buildingControllerMaintain/unitControllerMaintain',
                  'component': null,
                  'authority': null,
                  'redirect': null,
                  'code': 'unitControllerMaintain',
                  'appCode': 'unit-evc',
                  'label': null,
                  'url': null,
                  'id': '403hPMRIWFliIRzg4EDEw7',
                  'parentId': '6eXOE5t9aSlqd4vUiK8KYX',
                  'orderNum': 5,
                  'children': []
                }
              ]
            }
          ]
        },
        {
          'icon': 'abcd',
          'title': '场区风机配置',
          'href': '/fieldWindMachineConfig',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/baseInfoMaintain/fieldWindMachineConfig',
          'frontendRoutePath': '/intelligent-control/baseInfo/fieldWindMachineConfig',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'fieldWindMachineConfig',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '2lQvFPQLA6opy9fMqw1GIT',
          'parentId': '44PvV2T26BSfTPr4GDAnCN',
          'orderNum': 2,
          'children': [
            {
              'icon': 'abcd',
              'title': '风机数据库维护',
              'href': '/unitWindConfigManager',
              'spread': false,
              'path': '/bizManager/unit-evcbiz/baseInfoMaintain/201911201001',
              'frontendRoutePath': '/intelligent-control/baseInfo/fieldWindMachineConfig/fanDatabase',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'unitWindConfigManager',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '4llsp2b2jT293BsmXYsT5E',
              'parentId': '2lQvFPQLA6opy9fMqw1GIT',
              'orderNum': 4,
              'children': []
            },
            {
              'icon': 'abcd',
              'title': '场区风机配置管理',
              'href': '/unitWindConfigOperation',
              'spread': false,
              'path': '/bizManager/unit-evcbiz/baseInfoMaintain/unitWindConfigOperation',
              'frontendRoutePath': '/intelligent-control/baseInfo/fieldWindMachineConfig/configurationManagement',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'unitWindConfigOperation',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '5uyQD4zNRfBVXN67lqNpOl',
              'parentId': '2lQvFPQLA6opy9fMqw1GIT',
              'orderNum': 5,
              'children': []
            }
          ]
        },
        {
          'icon': 'abcd',
          'title': '告警推送管理',
          'href': '/alarmManage',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/baseInfoMaintain/alarmManage',
          'frontendRoutePath': '/intelligent-control/baseInfo/alarmManagement',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'alarmManage',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '5QnwgHsWhM2s3jpdHeeD8f',
          'parentId': '44PvV2T26BSfTPr4GDAnCN',
          'orderNum': 3,
          'children': [
            {
              'icon': 'abcd',
              'title': '报警暂停策略管理',
              'href': '/alarmSuspendStrategyManage',
              'spread': false,
              'path': '/bizManager/unit-evcbiz/baseInfoMaintain/alarmManage/alarmSuspendStrategyManage',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'alarmSuspendStrategyManage',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '7az6j5rfGuQcx7RqJsbXf3',
              'parentId': '5QnwgHsWhM2s3jpdHeeD8f',
              'orderNum': 1,
              'children': []
            },
            {
              'icon': 'abcd',
              'title': '报警暂停管理',
              'href': '/alarmSuspendManage',
              'spread': false,
              'path': '/bizManager/unit-evcbiz/baseInfoMaintain/alarmManage/alarmSuspendManage',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'alarmSuspendManage',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '2CoGeMAiAIyWXk8GeHzwSs',
              'parentId': '5QnwgHsWhM2s3jpdHeeD8f',
              'orderNum': 2,
              'children': []
            },
            {
              'icon': 'abcd',
              'title': '推送人员维护',
              'href': '/alarmNoticeUserManage',
              'spread': false,
              'path': '/bizManager/unit-evcbiz/baseInfoMaintain/alarmManage/alarmNoticeUserManage',
              'frontendRoutePath': '/intelligent-control/baseInfo/alarmManagement/targetMaintenance',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'alarmNoticeUserManage',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '22OhJCNS3tyqtNPR5NqFcp',
              'parentId': '5QnwgHsWhM2s3jpdHeeD8f',
              'orderNum': 3,
              'children': []
            },
            {
              'icon': 'abcd',
              'title': '告警系统配置',
              'href': '/alarmNoticeConfig',
              'spread': false,
              'path': '/bizManager/unit-evcbiz/baseInfoMaintain/alarmManage/alarmNoticeConfig',
              'frontendRoutePath': '/intelligent-control/baseInfo/alarmManagement/durationConfiguration',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'alarmNoticeConfig',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '4tQYoD3fLK82jInrJMnKSD',
              'parentId': '5QnwgHsWhM2s3jpdHeeD8f',
              'orderNum': 4,
              'children': []
            }
          ]
        },
        {
          'icon': 'abcd',
          'title': '设备参数模板',
          'href': '/deviceArgsTemplate',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/deviceArgsTemplate',
          'frontendRoutePath': '/intelligent-control/baseInfo/equipmentParameterTemplate',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'deviceArgsTemplate',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '5w8zUaq6juP2L5qOF7Ngsk',
          'parentId': '44PvV2T26BSfTPr4GDAnCN',
          'orderNum': 4,
          'children': []
        },
        {
          'icon': 'abcd',
          'title': '权限管理',
          'href': '/permissionManage',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/baseInfoMaintain/permissionManage',
          'frontendRoutePath': '/intelligent-control/baseInfo/systemAuthority',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'permissionManage',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '7EvinGwuHBR54mTQ48SRqF',
          'parentId': '44PvV2T26BSfTPr4GDAnCN',
          'orderNum': 6,
          'children': [
            {
              'icon': 'abcd',
              'title': '角色权限管理',
              'href': '/admin/group/unit-evc',
              'spread': false,
              'path': '/adminSys/baseManager/groupManager',
              'frontendRoutePath': '/intelligent-control/baseInfo/systemAuthority/rolePermission',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'unit-evcGroupManager',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '79CiR0G0aodpPCLc9sIxnd',
              'parentId': '7EvinGwuHBR54mTQ48SRqF',
              'orderNum': 2,
              'children': []
            },
            {
              'icon': 'abcd',
              'title': '数据权限管理',
              'href': '/admin/data/unit-evc',
              'spread': false,
              'path': '/adminSys/baseManager/dataManager',
              'frontendRoutePath': '/intelligent-control/baseInfo/systemAuthority/dataRights',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'unit-evcDataManager',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '3GgBpuTpNenXtKSg6OsAq8',
              'parentId': '7EvinGwuHBR54mTQ48SRqF',
              'orderNum': 3,
              'children': []
            },
            {
              'icon': 'abcd',
              'title': '用户权限反查',
              'href': '/permissionCheck',
              'spread': false,
              'path': '/bizManager/unit-evcbiz/baseInfoMaintain/permissionManage/permissionCheck',
              'frontendRoutePath': '/intelligent-control/baseInfo/systemAuthority/userReverseSearch',
              'component': null,
              'authority': null,
              'redirect': null,
              'code': 'permissionCheck',
              'appCode': 'unit-evc',
              'label': null,
              'url': null,
              'id': '3OF0WqdGbDf5RAjEJHMaxN',
              'parentId': '7EvinGwuHBR54mTQ48SRqF',
              'orderNum': 4,
              'children': []
            }
          ]
        }
      ]
    },
    {
      'icon': 'EvcOperatorTable',
      'title': '环控数据报表',
      'href': '/unit-evcOperatorTable',
      'spread': false,
      'path': '/bizManager/unit-evcbiz/unit-evcOperatorTable',
      'frontendRoutePath': '/intelligent-control/dataReport',
      'component': null,
      'authority': null,
      'redirect': null,
      'code': 'unit-evcOperatorTable',
      'appCode': 'unit-evc',
      'label': null,
      'url': null,
      'id': '3VYYGM14uHLRm8dITqDNZp',
      'parentId': '5Vcq9wmcrBB5vzVjBGoQvj',
      'orderNum': 7,
      'children': [
        {
          'icon': 'bar-chart',
          'title': '设备在线状况',
          'href': '/fieldDeviceOnlineStats',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcOperatorTable/fieldDeviceOnlineStats',
          'frontendRoutePath': '/intelligent-control/dataReport/onlineCondition',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'fieldDeviceOnlineStats',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '6PiMfhGgwP2RRHK16PYscT',
          'parentId': '3VYYGM14uHLRm8dITqDNZp',
          'orderNum': 1,
          'children': []
        },
        {
          'icon': 'area-chart',
          'title': '温湿度曲线图',
          'href': '/humiTemperatureTable',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcOperatorTable/humiTemperatureTable',
          'frontendRoutePath': '/intelligent-control/dataReport/humiture',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'humiTemperatureTable',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '3rJyimrHO2vPcT60P5cqPr',
          'parentId': '3VYYGM14uHLRm8dITqDNZp',
          'orderNum': 2,
          'children': []
        },
        {
          'icon': 'line-chart',
          'title': '设备故障统计',
          'href': '/fieldDeviceAlarmStats',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcOperatorTable/fieldDeviceAlarmStats',
          'frontendRoutePath': '/intelligent-control/dataReport/troubleCondition',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'fieldDeviceAlarmStats',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '2tTnYMBsMAb1BW28Jq4vdS',
          'parentId': '3VYYGM14uHLRm8dITqDNZp',
          'orderNum': 3,
          'children': []
        },
        {
          'icon': 'dot-chart',
          'title': '环境对比分析',
          'href': '/evcDataAnalysis',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcOperatorTable/evcDataAnalysis',
          'frontendRoutePath': '/intelligent-control/dataReport/environment',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'evcDataAnalysis',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '5RUGk8elCrSot1VXoiTPfY',
          'parentId': '3VYYGM14uHLRm8dITqDNZp',
          'orderNum': 4,
          'children': []
        },
        {
          'icon': 'pie-chart',
          'title': '参数变更统计',
          'href': '/paramChangeStats',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcOperatorTable/paramChangeStats',
          'frontendRoutePath': '/intelligent-control/dataReport/fieldParameter',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'paramChangeStats',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '5Qf95tyYwfIity013LSiix',
          'parentId': '3VYYGM14uHLRm8dITqDNZp',
          'orderNum': 5,
          'children': []
        },
        {
          'icon': 'lock',
          'title': '设备状态导出',
          'href': '/deviceStatusExport',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcOperatorTable/deviceStatusExport',
          'frontendRoutePath': '/intelligent-control/dataReport/equipment',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'deviceStatusExport',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '4NzRtk2nLTr9H3YW0vP3DS',
          'parentId': '3VYYGM14uHLRm8dITqDNZp',
          'orderNum': 8,
          'children': []
        },
        {
          'icon': 'lock',
          'title': '设备参数导出',
          'href': '/myEvcRuntimeArgs',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/myEvcRuntimeArgs',
          'frontendRoutePath': '/intelligent-control/dataReport/paramsExport',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'myEvcRuntimeArgs',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '6aEnTrglsxZpxaI9qSemRe',
          'parentId': '3VYYGM14uHLRm8dITqDNZp',
          'orderNum': 21,
          'children': []
        },
        {
          'icon': 'bar-chart',
          'title': '单元锁定情况',
          'href': '/fieldUnitLockStats',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcOperatorTable/fieldUnitLockStats',
          'frontendRoutePath': '/intelligent-control/dataReport/fieldLock',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'fieldUnitLockStats',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '2HLgfHJXeRyzQNJmSEl4Ep',
          'parentId': '3VYYGM14uHLRm8dITqDNZp',
          'orderNum': 22,
          'children': []
        },
        {
          'icon': 'lock',
          'title': '单元解锁统计',
          'href': '/UnitUnlockStatistics',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcOperatorTable/UnitUnlockStatistics',
          'frontendRoutePath': '/intelligent-control/dataReport/fieldUnlock',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'UnitUnlockStatistics',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '4GvpCGK2Uk4k65zrJcKg9J',
          'parentId': '3VYYGM14uHLRm8dITqDNZp',
          'orderNum': 23,
          'children': []
        },
        {
          'icon': 'lock',
          'title': '温湿探头统计',
          'href': '/UnitTempSeneorType',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcOperatorTable/UnitTempSeneorType',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'UnitTempSeneorType',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '4UW0T8uzvAsVH84M7o2B2j',
          'parentId': '3VYYGM14uHLRm8dITqDNZp',
          'orderNum': 24,
          'children': []
        }
      ]
    },
    {
      'icon': 'EvcLog',
      'title': '环控日志管理',
      'href': '/unit-evcLog',
      'spread': false,
      'path': '/bizManager/unit-evcbiz/unit-evcLog',
      'frontendRoutePath': '/intelligent-control/logManagement',
      'component': null,
      'authority': null,
      'redirect': null,
      'code': 'unit-evcLog',
      'appCode': 'unit-evc',
      'label': null,
      'url': null,
      'id': '6j8ZLFAPiqA1kvI4JnMMjH',
      'parentId': '5Vcq9wmcrBB5vzVjBGoQvj',
      'orderNum': 20,
      'children': [
        {
          'icon': 'sound',
          'title': '报警推送日志',
          'href': '/fieldAlarmLogs',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/fieldAlarmLogs',
          'frontendRoutePath': '/intelligent-control/logManagement/alarmPush',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'fieldAlarmLogs',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '7hfRre0hId0vgR5oe0WZJg',
          'parentId': '6j8ZLFAPiqA1kvI4JnMMjH',
          'orderNum': 8,
          'children': []
        },
        {
          'icon': 'abcd',
          'title': '场区指令日志',
          'href': '/fieldInstructionLogs',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/fieldInstructionLogs',
          'frontendRoutePath': '/intelligent-control/logManagement/fieldCommand',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'fieldInstructionLogs',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '4EWvdUWeZjpyyUhndc4i5U',
          'parentId': '6j8ZLFAPiqA1kvI4JnMMjH',
          'orderNum': 9,
          'children': []
        },
        {
          'icon': 'lock',
          'title': '场区告警日志',
          'href': '/alarmLog',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcLog/alarmLog',
          'frontendRoutePath': '/intelligent-control/logManagement/siteAlarm',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'alarmLog',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '47A1bZ8q6KncRG2s4nulV7',
          'parentId': '6j8ZLFAPiqA1kvI4JnMMjH',
          'orderNum': 10,
          'children': []
        },
        {
          'icon': 'lock',
          'title': '告警合并日志',
          'href': '/alarmUnionLog',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcLog/alarmUnionLog',
          'frontendRoutePath': '/intelligent-control/logManagement/alarmLogMerge',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'alarmUnionLog',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '6zAvoeDlLKhzGE3mBAK8j5',
          'parentId': '6j8ZLFAPiqA1kvI4JnMMjH',
          'orderNum': 11,
          'children': []
        },
        {
          'icon': 'lock',
          'title': '参数变更日志',
          'href': '/paramChangeLog',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcLog/paramChangeLog',
          'frontendRoutePath': '/intelligent-control/logManagement/parameterChange',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'paramChangeLog',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '7eCzeAUJB67LRuBEUyXXk6',
          'parentId': '6j8ZLFAPiqA1kvI4JnMMjH',
          'orderNum': 12,
          'children': []
        }
      ]
    },
    {
      'icon': 'Basic-Configuration',
      'title': '基础配置管理',
      'href': '/unit-evcBaseManager',
      'spread': false,
      'path': '/bizManager/unit-evcbiz/unit-evcManager',
      'frontendRoutePath': '/intelligent-control/baseDeploy',
      'component': null,
      'authority': null,
      'redirect': null,
      'code': 'unit-evcManager',
      'appCode': 'unit-evc',
      'label': null,
      'url': null,
      'id': '3WpXLdWtss9bDS0qtk6EFb',
      'parentId': '5Vcq9wmcrBB5vzVjBGoQvj',
      'orderNum': 1,
      'children': [
        {
          'icon': 'bar-chart',
          'title': '菜单管理',
          'href': '/admin/menu/unit-evc',
          'spread': false,
          'path': '/adminSys/baseManager/menuManager',
          'frontendRoutePath': '/intelligent-control/baseDeploy/menuManager',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'unit-evcMenuManager',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '5nlSfLpbZmlVzpHWdOzkJR',
          'parentId': '3WpXLdWtss9bDS0qtk6EFb',
          'orderNum': 1,
          'children': []
        },
        {
          'icon': 'bar-chart',
          'title': '数据接口',
          'href': '/admin/datainterface/unit-evc',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/unit-evcDataInterface',
          'frontendRoutePath': '/intelligent-control/baseDeploy/dataInterface',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'unit-evcDataInterface',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '4YW2FAhuwOPBVJwYXQmj4N',
          'parentId': '3WpXLdWtss9bDS0qtk6EFb',
          'orderNum': 30,
          'children': []
        }
      ]
    },
    {
      'icon': 'unlock',
      'title': '楼房场区概览',
      'href': '/buildingPigHouse',
      'spread': false,
      'path': '/bizManager/unit-evcbiz/buildingPigHouse',
      'component': null,
      'authority': null,
      'redirect': null,
      'code': 'buildingPigHouse',
      'appCode': 'unit-evc',
      'label': null,
      'url': null,
      'id': '6wvT4st9YdTE8XX1jVxXQa',
      'parentId': '5Vcq9wmcrBB5vzVjBGoQvj',
      'orderNum': 21,
      'children': []
    },
    {
      'icon': 'lock',
      'title': '自动检测任务',
      'href': '/autoCheck',
      'spread': false,
      'path': '/bizManager/unit-evcbiz/autoCheck',
      'component': null,
      'authority': null,
      'redirect': null,
      'code': 'autoCheckTask',
      'appCode': 'unit-evc',
      'label': null,
      'url': null,
      'id': '5hz7PHi9bxZh8nue3Ej7VA',
      'parentId': '5Vcq9wmcrBB5vzVjBGoQvj',
      'orderNum': 22,
      'children': [
        {
          'icon': 'lock',
          'title': '空气过滤检测',
          'href': '/airfilterCheck',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/autoCheck/airfilterCheck',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'airfilterCheck',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '5lzDHn2VGnHPt345jfqN01',
          'parentId': '5hz7PHi9bxZh8nue3Ej7VA',
          'orderNum': 1,
          'children': []
        },
        {
          'icon': 'lock',
          'title': '场区告警自检',
          'href': '/unitAlarmSystemCheck',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/autoTask/unitAlarmSystemCheck',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'unitAlarmSystemCheck',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '5p0wpgt1RrOZkzFkLRmJjX',
          'parentId': '5hz7PHi9bxZh8nue3Ej7VA',
          'orderNum': 2,
          'children': []
        },
        {
          'icon': 'lock',
          'title': '风量关系测算',
          'href': '/airVolumeCheck',
          'spread': false,
          'path': '/bizManager/unit-evcbiz/autoCheck/airVolumeCheck',
          'component': null,
          'authority': null,
          'redirect': null,
          'code': 'airVolumeCheck',
          'appCode': 'unit-evc',
          'label': null,
          'url': null,
          'id': '5nez5czCtw9ZuSBqo4wIU9',
          'parentId': '5hz7PHi9bxZh8nue3Ej7VA',
          'orderNum': 3,
          'children': []
        }
      ]
    },
    {
      'icon': 'lock',
      'title': '电表数据导出',
      'href': '/EleMeter',
      'spread': false,
      'path': '/bizManager/unit-evcbiz/EleMeter',
      'component': null,
      'authority': null,
      'redirect': null,
      'code': 'EleMeter',
      'appCode': 'unit-evc',
      'label': null,
      'url': null,
      'id': '23lQViY9XCARdN0TavKzCY',
      'parentId': '5Vcq9wmcrBB5vzVjBGoQvj',
      'orderNum': 28,
      'children': []
    }
  ]
}

export default menuLsit
